name: anchore-analysis

on:
  workflow_call:
    inputs:
      docker_image_name:
        description: Name of the Docker image
        default: paniclobster
        required: false
        type: string

jobs:
  anchore-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2.3.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Build the Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          load: true
          push: false
          tags: ${{ inputs.docker_image_name }}:latest
      - name: Perform Anchore analysis
        uses: anchore/scan-action@v3.1.0
        with:
          acs-report-enable: true
          fail-build: false
          image: ${{ inputs.docker_image_name }}:latest
      - name: Upload Anchore report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
