name: dependabot-automerge

on:
  workflow_call:
    secrets:
      automerge_github_token:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-automerge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Fetch Dependabot metadata
        uses: dependabot/fetch-metadata@v1.3.1
        with:
          github-token: ${{ secrets.automerge_github_token }}
      - name: Auto approve pull request
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.automerge_github_token }}
      - name: Auto merge pull request
        run: gh pr merge --auto --delete-branch --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.automerge_github_token }}
