name: docker-build

on:
  workflow_call:
    inputs:
      docker_build_context:
        description: Context of the Docker build
        default: .
        required: false
        type: string

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2.4.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Build the Docker image
        uses: docker/build-push-action@v2.8.0
        with:
          context: ${{ inputs.docker_build_context }}
          push: false
