name: docker-build-publish

on:
  workflow_call:
    inputs:
      docker_build_context:
        description: Context of the Docker build
        default: .
        required: false
        type: string
      docker_image_name:
        description: Name of the Docker image
        required: true
        type: string
      docker_image_tag_prefix:
        description: Prefix of the Docker image tag
        default: ""
        required: false
        type: string
      docker_image_tag_suffix:
        description: Suffix of the Docker image tag
        default: ""
        required: false
        type: string
    secrets:
      docker_login_registry:
        required: true
      docker_login_username:
        required: true
      docker_login_password:
        required: true

jobs:
  docker-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1
      - name: Login to Docker Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ secrets.docker_login_registry }}
          username: ${{ secrets.docker_login_username }}
          password: ${{ secrets.docker_login_password }}
      - name: Get release version
        id: get_release_version
        run: echo "tags=${GITHUB_REF#refs/*/v}" >> $GITHUB_OUTPUT
      - name: Build and Push the Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: ${{ inputs.docker_build_context }}
          load: false
          push: true
          tags: ${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag_prefix }}${{ steps.get_release_version.outputs.tags }}${{ inputs.docker_image_tag_suffix }},${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag_prefix }}latest${{ inputs.docker_image_tag_suffix }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
