name: docker-build

on:
  workflow_call:
    inputs:
      docker_build_context:
        description: Context of the Docker build
        default: .
        required: false
        type: string

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.0.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Build the Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: ${{ inputs.docker_build_context }}
          load: true
          push: false
