name: docker-anchore-analysis

on:
  workflow_call:
    inputs:
      docker_build_context:
        description: Context of the Docker build
        default: .
        required: false
        type: string
      docker_image_name:
        description: Name of the Docker image
        required: true
        type: string
      docker_image_tag_prefix:
        description: Prefix of the Docker image tag
        default: ""
        required: false
        type: string
      docker_image_tag_suffix:
        description: Suffix of the Docker image tag
        default: ""
        required: false
        type: string

jobs:
  docker-anchore-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.3.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.3.0
      - name: Build and Load the Docker image
        uses: docker/build-push-action@v3.3.0
        with:
          context: ${{ inputs.docker_build_context }}
          load: true
          push: false
          tags: ${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag_prefix }}latest${{ inputs.docker_image_tag_suffix }}
      - name: Perform Anchore analysis
        uses: anchore/scan-action@v3.3.3
        with:
          acs-report-enable: true
          fail-build: false
          image: ${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag_prefix }}latest${{ inputs.docker_image_tag_suffix }}
      - name: Upload Anchore report
        uses: github/codeql-action/upload-sarif@v2.2.1
        with:
          sarif_file: results.sarif
