name: docker-build-publish

on:
  workflow_call:
    inputs:
      docker_build_context:
        description: Context of the Docker build
        default: .
        required: false
        type: string
      docker_image_name:
        description: Name of the Docker image
        required: true
        type: string
      docker_image_tag_prefix:
        description: Prefix of the Docker image tag
        default: ""
        required: false
        type: string
      docker_image_tag_suffix:
        description: Suffix of the Docker image tag
        default: ""
        required: false
        type: string
    secrets:
      docker_hub_username:
        required: true
      docker_hub_password:
        required: true

jobs:
  docker-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.0.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.docker_hub_username }}
          password: ${{ secrets.docker_hub_password }}
      - name: Get release version
        id: get_release_version
        run: echo ::set-output name=tags::${GITHUB_REF#refs/*/v}
      - name: Build and Push the Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: ${{ inputs.docker_build_context }}
          push: true
          tags: ${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag_prefix }}${{ steps.get_release_version.outputs.tags }}${{ inputs.docker_image_tag_suffix }},${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag_prefix }}latest${{ inputs.docker_image_tag_suffix }}
